In [19]:
import seaborn as sns
import pandas as pd
import matplotlib as plt

In [3]:
data = pd.read_csv('INFORM Risk 2024.csv')

In [4]:
data.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41
0,COUNTRY,ISO3,INFORM RISK,RISK CLASS,Rank,Lack of Reliability (*),HAZARD & EXPOSURE,Natural,Earthquake,River Flood,...,DRR,Governance,Infrastructure,Communication,Physical infrastructure,Access to health care,Number of Missing Indicators,% of Missing Indicators,Countries in HVC,Recentness data (average years)
1,(a-z),(a-z),(0-10),(Very Low-Very High),(1-191),(0-10),(0-10),(0-10),(0-10),(0-10),...,(0-10),(0-10),(0-10),(0-10),(0-10),(0-10),(0-50),(0-100%),(Yes/No),()
2,Afghanistan,AFG,8.1,Very High,4,-187.4,8.7,5.7,8.7,7.3,...,6.3,8.0,7.0,6.3,6.5,8.1,4,8%,YES,-28.31
3,Albania,ALB,3.1,Low,104,-156.3,3.4,5.7,8.3,4.6,...,x,5.7,2.3,2.0,1.4,3.4,6,12%,NaN,-29.61
4,Algeria,DZA,3.6,Medium,81,-144.2,3.8,3.2,7.9,3.6,...,3.5,6.5,3.7,2.9,4.1,4.1,0,0%,NaN,-27.04

In [10]:
header = data.iloc[0]
data = data[2:]
data.columns = header

In [12]:
data.head()

,COUNTRY,ISO3,INFORM RISK,RISK CLASS,Rank,Lack of Reliability (*),HAZARD & EXPOSURE,Natural,Earthquake,River Flood,...,DRR,Governance,Infrastructure,Communication,Physical infrastructure,Access to health care,Number of Missing Indicators,% of Missing Indicators,Countries in HVC,Recentness data (average years)
2,Afghanistan,AFG,8.1,Very High,4,-187.4,8.7,5.7,8.7,7.3,...,6.3,8.0,7.0,6.3,6.5,8.1,4,8%,YES,-28.31
3,Albania,ALB,3.1,Low,104,-156.3,3.4,5.7,8.3,4.6,...,x,5.7,2.3,2.0,1.4,3.4,6,12%,NaN,-29.61
4,Algeria,DZA,3.6,Medium,81,-144.2,3.8,3.2,7.9,3.6,...,3.5,6.5,3.7,2.9,4.1,4.1,0,0%,NaN,-27.04
5,Angola,AGO,5.2,High,32,-142.3,4.2,2.9,0.1,3.9,...,5.2,6.9,7.3,6.3,7.9,7.8,0,0%,NaN,-26.69
6,Antigua and Barbuda,ATG,2.3,Low,151,-183.8,2.0,3.7,5.1,0.0,...,5.4,5.3,1.3,0.2,0.7,3.1,18,35%,NaN,-35.21

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 2 to 192
Data columns (total 42 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   COUNTRY                                    191 non-null    object
 1   ISO3                                       191 non-null    object
 2   INFORM RISK                                191 non-null    object
 3   RISK CLASS                                 191 non-null    object
 4   Rank                                       191 non-null    object
 5   Lack of Reliability (*)                    191 non-null    object
 6   HAZARD & EXPOSURE                          191 non-null    object
 7   Natural                                    191 non-null    object
 8   Earthquake                                 191 non-null    object
 9   River Flood                                191 non-null    object
 10  Tsunami                                    191 non-null    object
 11  Tropical Cyclone                           191 non-null    object
 12  Coastal flood                              191 non-null    object
 13  Drought                                    191 non-null    object
 14  Epidemic                                   191 non-null    object
 15  Human                                      191 non-null    object
 16  Projected Conflict Risk                    191 non-null    object
 17  Current Highly Violent Conflict Intensity  191 non-null    object
 18  VULNERABILITY                              191 non-null    object
 19  Socio-Economic Vulnerability               191 non-null    object
 20  Development & Deprivation                  191 non-null    object
 21  Inequality                                 191 non-null    object
 22  Economic Dependency                        191 non-null    object
 23  Vulnerable Groups                          191 non-null    object
 24  Uprooted people                            191 non-null    object
 25  Health Conditions                          191 non-null    object
 26  Children U5                                191 non-null    object
 27  Recent Shocks                              191 non-null    object
 28  Food Security                              191 non-null    object
 29  Other Vulnerable Groups                    191 non-null    object
 30  LACK OF COPING CAPACITY                    191 non-null    object
 31  Institutional                              191 non-null    object
 32  DRR                                        191 non-null    object
 33  Governance                                 191 non-null    object
 34  Infrastructure                             191 non-null    object
 35  Communication                              191 non-null    object
 36  Physical infrastructure                    191 non-null    object
 37  Access to health care                      191 non-null    object
 38  Number of Missing Indicators               191 non-null    object
 39  % of Missing Indicators                    191 non-null    object
 40  Countries in HVC                           28 non-null     object
 41  Recentness data (average years)            191 non-null    object
dtypes: object(42)
memory usage: 62.8+ KB

In [42]:
for column in data.columns:
    print(data[column][2], type(data[column][2]))

Afghanistan <class 'str'>
AFG <class 'str'>
8.1 <class 'str'>
Very High <class 'str'>
4 <class 'str'>
-187.4 <class 'str'>
8.7 <class 'str'>
5.7 <class 'str'>
8.7 <class 'str'>
7.3 <class 'str'>
0.0 <class 'str'>
0.0 <class 'str'>
0.0 <class 'str'>
8.6 <class 'str'>
6.9 <class 'str'>
10.0 <class 'str'>
10.0 <class 'str'>
10.0 <class 'str'>
8.5 <class 'str'>
8.3 <class 'str'>
8.7 <class 'str'>
9.0 <class 'str'>
6.9 <class 'str'>
8.6 <class 'str'>
10.0 <class 'str'>
2.0 <class 'str'>
4.3 <class 'str'>
7.3 <class 'str'>
7.1 <class 'str'>
5.6 <class 'str'>
7.1 <class 'str'>
7.2 <class 'str'>
6.3 <class 'str'>
8.0 <class 'str'>
7.0 <class 'str'>
6.3 <class 'str'>
6.5 <class 'str'>
8.1 <class 'str'>
4 <class 'str'>
8% <class 'str'>
YES <class 'str'>
-28.31 <class 'str'>

In [88]:
data.replace('x', 0, inplace=True)

In [104]:
for col in data.columns[4:39]:
    data[col].astype(float)

ValueError: could not convert string to float: '#ERROR!'

In [ ]:
df = data.copy()
df = df[df.columns[4:39]]
print(df)
#for col in df:
    #pd.to_numeric(df[col])

In [22]:
corr = data.corr(numeric_only=True)
corr
#sns.heatmap(data=corr,vmin=-1,vmax=1,annot=True)

Empty DataFrame
Columns: []
Index: []